"""alter payments fields

Revision ID: 09d4e29ee105
Revises: 0b19d934fe88
Create Date: 2026-07-14 19:48:54.476887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d4e29ee105'
down_revision: Union[str, Sequence[str], None] = '0b19d934fe88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'm3')
    op.drop_column('payments', 'value_m3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('value_m3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('m3', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
