"""alter tables and relationships

Revision ID: 0b19d934fe88
Revises: 823ce4f30155
Create Date: 2026-07-13 10:36:10.193024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "0b19d934fe88"
down_revision: Union[str, Sequence[str], None] = "823ce4f30155"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("origin_id", sa.Uuid(), nullable=False))
    op.add_column("jobs", sa.Column("destiny_id", sa.Uuid(), nullable=False))
    op.add_column("jobs", sa.Column("material_id", sa.Uuid(), nullable=False))
    op.add_column("jobs", sa.Column("quantity", sa.Float(), nullable=False))
    op.add_column(
        "jobs", sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "jobs",
        sa.Column(
            "value_type",
            sa.String(length=50),
            server_default="per_quantity",
            nullable=False,
        ),
    )
    op.add_column("jobs", sa.Column("rate", sa.Float(), nullable=False))
    op.add_column("jobs", sa.Column("value", sa.Float(), nullable=False))
    op.drop_index(op.f("ix_jobs_destiny"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_origin"), table_name="jobs")
    op.create_index(op.f("ix_jobs_destiny_id"), "jobs", ["destiny_id"], unique=False)
    op.create_index(op.f("ix_jobs_material_id"), "jobs", ["material_id"], unique=False)
    op.create_index(op.f("ix_jobs_origin_id"), "jobs", ["origin_id"], unique=False)
    op.drop_constraint(op.f("jobs_origin_fkey"), "jobs", type_="foreignkey")
    op.drop_constraint(op.f("jobs_destiny_fkey"), "jobs", type_="foreignkey")
    op.create_foreign_key(None, "jobs", "materials", ["material_id"], ["id"])
    op.create_foreign_key(None, "jobs", "works", ["origin_id"], ["id"])
    op.create_foreign_key(None, "jobs", "works", ["destiny_id"], ["id"])
    op.drop_column("jobs", "destiny")
    op.drop_column("jobs", "origin")
    op.add_column(
        "materials",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "materials",
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "materials",
        sa.Column("material_class", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "materials",
        sa.Column("packaging", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "materials",
        sa.Column("technology", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("materials", "value_m3")
    op.drop_column("materials", "description")
    op.drop_index(op.f("ix_statements_material_id"), table_name="statements")
    op.drop_constraint(
        op.f("statements_material_id_fkey"), "statements", type_="foreignkey"
    )
    op.drop_column("statements", "m3")
    op.drop_column("statements", "material_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "statements",
        sa.Column("material_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "statements", sa.Column("m3", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("statements_material_id_fkey"),
        "statements",
        "materials",
        ["material_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_statements_material_id"), "statements", ["material_id"], unique=False
    )
    op.add_column(
        "materials",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "materials",
        sa.Column(
            "value_m3",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("materials", "technology")
    op.drop_column("materials", "packaging")
    op.drop_column("materials", "material_class")
    op.drop_column("materials", "state")
    op.drop_column("materials", "code")
    op.add_column(
        "jobs", sa.Column("origin", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "jobs", sa.Column("destiny", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.create_foreign_key(
        op.f("jobs_destiny_fkey"), "jobs", "works", ["destiny"], ["id"]
    )
    op.create_foreign_key(op.f("jobs_origin_fkey"), "jobs", "works", ["origin"], ["id"])
    op.drop_index(op.f("ix_jobs_origin_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_material_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_destiny_id"), table_name="jobs")
    op.create_index(op.f("ix_jobs_origin"), "jobs", ["origin"], unique=False)
    op.create_index(op.f("ix_jobs_destiny"), "jobs", ["destiny"], unique=False)
    op.drop_column("jobs", "value")
    op.drop_column("jobs", "rate")
    op.drop_column("jobs", "value_type")
    op.drop_column("jobs", "unit")
    op.drop_column("jobs", "quantity")
    op.drop_column("jobs", "material_id")
    op.drop_column("jobs", "destiny_id")
    op.drop_column("jobs", "origin_id")
    # ### end Alembic commands ###
