"""update statement_id field

Revision ID: 132132355499
Revises: 654e33f1c892
Create Date: 2026-05-07 23:04:43.733656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132132355499'
down_revision: Union[str, Sequence[str], None] = '654e33f1c892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'statement_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'statement_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
