"""add materials and payments

Revision ID: 3a9d52474716
Revises: f16eaa6bcdc0
Create Date: 2026-04-16 13:06:12.567396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "3a9d52474716"
down_revision: Union[str, Sequence[str], None] = "f16eaa6bcdc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("value_m3", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("m3", sa.Integer(), nullable=False),
        sa.Column("value_m3", sa.Float(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="pending", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_job_id"), "payments", ["job_id"], unique=True)
    op.add_column(
        "cars",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.alter_column("cars", "fuel", existing_type=sa.VARCHAR(), nullable=False)
    op.add_column("jobs", sa.Column("statement_id", sa.Uuid(), nullable=False))
    op.alter_column(
        "jobs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "jobs",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=True,
    )
    op.create_unique_constraint(None, "jobs", ["statement_id"])
    op.create_foreign_key(None, "jobs", "statements", ["statement_id"], ["id"])
    op.drop_column("jobs", "m3")
    op.add_column(
        "statements",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("statements", sa.Column("material_id", sa.Uuid(), nullable=False))
    op.add_column("statements", sa.Column("m3", sa.Integer(), nullable=False))
    op.add_column(
        "statements",
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "statements", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(op.f("statements_job_id_key"), "statements", type_="unique")
    op.create_index(op.f("ix_statements_code"), "statements", ["code"], unique=False)
    op.create_index(
        op.f("ix_statements_material_id"), "statements", ["material_id"], unique=False
    )
    op.drop_constraint(op.f("statements_job_id_fkey"), "statements", type_="foreignkey")
    op.create_foreign_key(None, "statements", "materials", ["material_id"], ["id"])
    op.drop_column("statements", "job_id")
    op.add_column("works", sa.Column("active", sa.Boolean(), nullable=False))
    op.add_column(
        "works",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "works", sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.alter_column("works", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("works", "image_url")
    op.drop_column("works", "budget")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "works", sa.Column("budget", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "works",
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column("works", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("works", "image")
    op.drop_column("works", "created_at")
    op.drop_column("works", "active")
    op.add_column(
        "statements",
        sa.Column("job_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "statements", type_="foreignkey")
    op.create_foreign_key(
        op.f("statements_job_id_fkey"), "statements", "jobs", ["job_id"], ["id"]
    )
    op.drop_index(op.f("ix_statements_material_id"), table_name="statements")
    op.drop_index(op.f("ix_statements_code"), table_name="statements")
    op.create_unique_constraint(
        op.f("statements_job_id_key"),
        "statements",
        ["job_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("statements", "updated_at")
    op.drop_column("statements", "active")
    op.drop_column("statements", "m3")
    op.drop_column("statements", "material_id")
    op.drop_column("statements", "code")
    op.add_column(
        "jobs", sa.Column("m3", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.drop_constraint(None, "jobs", type_="unique")
    op.alter_column(
        "jobs",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "jobs",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.drop_column("jobs", "statement_id")
    op.alter_column("cars", "fuel", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("cars", "created_at")
    op.drop_index(op.f("ix_payments_job_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_table("materials")
    # ### end Alembic commands ###
