"""add code work field

Revision ID: 48e77088b06d
Revises: 3a9d52474716
Create Date: 2026-05-07 13:34:37.793519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "48e77088b06d"
down_revision: Union[str, Sequence[str], None] = "3a9d52474716"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("statements", "code", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_statements_code"), table_name="statements")
    op.add_column(
        "works", sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "works", sa.Column("cnpj", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_index(op.f("ix_works_code"), "works", ["code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_works_code"), table_name="works")
    op.drop_column("works", "cnpj")
    op.drop_column("works", "code")
    op.create_index(op.f("ix_statements_code"), "statements", ["code"], unique=False)
    op.alter_column("statements", "code", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
