"""update work table

Revision ID: 654e33f1c892
Revises: 3003ba419d22
Create Date: 2026-05-07 15:48:41.578943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "654e33f1c892"
down_revision: Union[str, Sequence[str], None] = "3003ba419d22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "works",
        sa.Column("zip_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("works", "region")
    op.drop_column("works", "active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "works", sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "works", sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("works", "zip_code")
    # ### end Alembic commands ###
