"""add carrier and job relationship

Revision ID: 68565d9d3100
Revises: baa8f88a8e38
Create Date: 2026-05-28 13:35:59.242811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "68565d9d3100"
down_revision: Union[str, Sequence[str], None] = "baa8f88a8e38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carriers",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cnpj", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("zip_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_carriers_code"), "carriers", ["code"], unique=False)
    op.create_index(op.f("ix_carriers_name"), "carriers", ["name"], unique=False)
    op.drop_index(op.f("ix_carries_code"), table_name="carries")
    op.drop_index(op.f("ix_carries_name"), table_name="carries")
    op.drop_table("carries")
    op.add_column("jobs", sa.Column("carrier_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_jobs_carrier_id"), "jobs", ["carrier_id"], unique=False)
    op.create_foreign_key(None, "jobs", "carriers", ["carrier_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.drop_index(op.f("ix_jobs_carrier_id"), table_name="jobs")
    op.drop_column("jobs", "carrier_id")
    op.create_table(
        "carries",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("cnpj", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("zip_code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("state", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("carries_pkey")),
    )
    op.create_index(op.f("ix_carries_name"), "carries", ["name"], unique=False)
    op.create_index(op.f("ix_carries_code"), "carries", ["code"], unique=False)
    op.drop_index(op.f("ix_carriers_name"), table_name="carriers")
    op.drop_index(op.f("ix_carriers_code"), table_name="carriers")
    op.drop_table("carriers")
    # ### end Alembic commands ###
