"""add new modules

Revision ID: c89c8773d2b2
Revises: 139803dfcc80
Create Date: 2026-04-06 20:03:36.153297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c89c8773d2b2"
down_revision: Union[str, Sequence[str], None] = "139803dfcc80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("manufacture", sa.Integer(), nullable=True),
        sa.Column("km", sa.Integer(), nullable=True),
        sa.Column("fuel", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("strength", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("capacity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("versatility", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cars_license"), "cars", ["license"], unique=True)
    op.create_table(
        "works",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("budget", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_works_name"), "works", ["name"], unique=False)
    op.create_table(
        "jobs",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("origin", sa.Uuid(), nullable=False),
        sa.Column("destiny", sa.Uuid(), nullable=False),
        sa.Column("car_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("m3", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["cars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["destiny"],
            ["works.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin"],
            ["works.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_car_id"), "jobs", ["car_id"], unique=False)
    op.create_index(op.f("ix_jobs_created_by"), "jobs", ["created_by"], unique=False)
    op.create_index(op.f("ix_jobs_destiny"), "jobs", ["destiny"], unique=False)
    op.create_index(op.f("ix_jobs_origin"), "jobs", ["origin"], unique=False)
    op.create_table(
        "statements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("statements")
    op.drop_index(op.f("ix_jobs_origin"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_destiny"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_created_by"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_car_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_works_name"), table_name="works")
    op.drop_table("works")
    op.drop_index(op.f("ix_cars_license"), table_name="cars")
    op.drop_table("cars")
    # ### end Alembic commands ###
