"""add type driver in users

Revision ID: e9917c02f569
Revises: c89c8773d2b2
Create Date: 2026-04-13 15:02:38.753840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9917c02f569'
down_revision: Union[str, Sequence[str], None] = 'c89c8773d2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('driver_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_jobs_driver_id'), 'jobs', ['driver_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['driver_id'], ['id'])
    op.alter_column('statements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statements', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_driver_id'), table_name='jobs')
    op.drop_column('jobs', 'driver_id')
    # ### end Alembic commands ###
