"""add fields users table

Revision ID: f16eaa6bcdc0
Revises: e9917c02f569
Create Date: 2026-04-15 21:22:55.570426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f16eaa6bcdc0"
down_revision: Union[str, Sequence[str], None] = "e9917c02f569"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("cpf", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone")
    op.drop_column("users", "cpf")
    # ### end Alembic commands ###
